//! Raw FFI bindings to libwpe, WPE WebKit, and wpebackend-fdo.
//!
//! This crate provides low-level bindings generated by bindgen.
//! For a safe Rust API, use the `wpe` crate instead.
//!
//! ## Required system packages
//!
//! On Arch Linux / Artix:
//! ```sh
//! pacman -S libwpe wpewebkit wpebackend-fdo
//! ```

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
